CUDA_VISIBLE_DEVICES=0 deepspeed --master_port=24998 ./quick_demo.py \
--epochs=1 \
--steps_per_epoch=1 \
--grad_accumulation_steps=1 \
--batch_size=1 \
--version="llava-med-v1.5-mistral-7b_path" \
--dataset_dir='' \
--vision_pretrained="medsam_vit_b_path" \
--dataset="seg_med_2d||reasoning_med_seg" \
--seg_med_2d_data="SAMed2D" \
--reasoning_med_seg_data="ReasoningMedSeg" \
--sample_rates="7,2" \
--exp_name="xxxxxx" \
--conv_type="mistral_instruct" \
--weight="" \
--eval_only 
